name: Client Quality
on:
  workflow_call:
    inputs:
      # Skipping needs to happen at the job level, otherwise
      # Github will keep waiting for status checks
      skip:
        required: false
        type: boolean
        default: false

jobs:
  client-quality:
    if: inputs.skip != true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - uses: actions/setup-node@1d0ff469b7ec7b3cb9d8673fde0c81c44821de2a # v4.2.0
        with:
          node-version: 21
          cache: 'yarn'
      - run: yarn install
      - run: yarn prettier-check
      - run: NODE_OPTIONS="--max-old-space-size=4096" yarn workspace workflowai build
      - run: yarn workspace workflowai test
